### ISSUE TITLE
P326 UserProfileContainerクラスのパスが本書と異なる

### ISSUE THREAD

**Issue by shinriyo** [gihyo-book/ts-nextbook-app#15]
P326 UserProfileContainerクラスのパスが本書と異なってます。

**・本書**
`src/components/UserProfileContainer.tsx`

正誤表にはありませんでした。
https://gihyo.jp/book/2022/978-4-297-12916-3/support

**・コード**
`src/containers/UserProfileContainer.tsx`
概要GitHub
https://github.com/gihyo-book/ts-nextbook-app/blob/main/src/containers/UserProfileContainer.tsx

**Comment by tamanyan** [comment]
第3刷にて修正済のためクローズさせて頂きます。ご報告ありがとうございました。

**Comment by tamanyan** [comment]
正誤表への反映依頼は私から技術評論社に伝えさせて頂きます！
