### ISSUE TITLE
P327 UserProductCardListContainerクラスのパスが本書と異なる

### ISSUE THREAD

**Issue by shinriyo** [gihyo-book/ts-nextbook-app#16]
P327 UserProfileContainerクラスのパスが本書と異なってます。

**・本書**
`src/components/UserProductCardListContainer.tsx`

正誤表にはありませんでした。
https://gihyo.jp/book/2022/978-4-297-12916-3/support

**・コード**
`src/containers/UserProductCardListContainer.tsx`
概要GitHub
https://github.com/gihyo-book/ts-nextbook-app/blob/main/src/containers/UserProductCardListContainer.tsx

**Comment by tamanyan** [comment]
第3刷にて修正済のためクローズさせて頂きます。ご報告ありがとうございました。
