### ISSUE TITLE
P341 AddToCartButtonContainerクラスのパスが本書と異なっている

### ISSUE THREAD

**Issue by shinriyo** [gihyo-book/ts-nextbook-app#17]
P341 AddToCartButtonContainerクラスのパスが本書と異なってます。

**・本書**
`src/components/AddToCartButtonContainer.tsx`

正誤表にはありませんでした。
https://gihyo.jp/book/2022/978-4-297-12916-3/support

**・コード**
`src/containers/AddToCartButtonContainer.tsx`
概要GitHub
https://github.com/gihyo-book/ts-nextbook-app/blob/main/src/containers/AddToCartButtonContainer.tsx

**Comment by tamanyan** [comment]
第3刷にて修正済のためクローズさせて頂きます。ご報告ありがとうございました。
